services:
  - type: web
    name: globalvariablesapi
    env: java
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/global-variables-api-1.0.0.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
